import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedRectangle4019Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedGroup49Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedPersonundefinedWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedLetssyouinWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedEllipse55Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedEllipse55Widget2.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedSkipWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget/generated/GeneratedOrWidget.dart';

/* Frame change sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChangesignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 358.0,
                child: GeneratedRectangle4019Widget(),
              ),
              Positioned(
                left: null,
                top: 362.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.50, y: 0.00, z: 0, child: GeneratedLetssyouinWidget()),
              ),
              Positioned(
                left: null,
                top: 662.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: -8.50, y: 0.00, z: 0, child: GeneratedOrWidget()),
              ),
              Positioned(
                left: 28.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup49Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 213.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget2(),
              ),
              Positioned(
                left: 203.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 701.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPersonundefinedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.192,
                        translateY: constraints.maxHeight * 0.7327586206896551,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget16())
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 23.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: 145.00, y: 0.00, z: 0, child: GeneratedSkipWidget()),
              )
            ]),
      ),
    ));
  }
}
