import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget1/generated/GeneratedGroup34Widget1.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget1/generated/GeneratedBarWidget9.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget1/generated/GeneratedNavbarWidget15.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget1/generated/GeneratedMYTIPSWidget.dart';

/* Frame tipsloker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipslokerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget15()),
              ),
              Positioned(
                left: null,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 590.0,
                child: GeneratedGroup34Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 35.0,
                child: GeneratedMYTIPSWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget9(),
              )
            ]),
      ),
    ));
  }
}
