import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup62Widget5.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup64Widget9.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup60Widget6.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedBarWidget22.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/Generated1fileWidget2.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedPOSTJOBVACANCIESWidget2.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup61Widget6.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup59Widget5.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget2/generated/GeneratedGroup134Widget6.dart';

/* Frame pasang iklan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPasangiklanWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 654.0,
                child: Generated1fileWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget22(),
              ),
              Positioned(
                left: 33.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 70.0,
                child: GeneratedPOSTJOBVACANCIESWidget2(),
              ),
              Positioned(
                left: 188.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup63Widget1(),
              ),
              Positioned(
                left: 188.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup64Widget9(),
              ),
              Positioned(
                left: 32.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup59Widget5(),
              ),
              Positioned(
                left: 188.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup60Widget6(),
              ),
              Positioned(
                left: 32.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup61Widget6(),
              ),
              Positioned(
                left: 32.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 143.73521423339844,
                height: 143.00003051757812,
                child: GeneratedGroup62Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedGroup134Widget6(),
              )
            ]),
      ),
    ));
  }
}
