import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedBlurWidget44.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedUsharealtWidget5.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedRectangle31Widget9.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/Generatedonyour_markWidget9.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedCreateanewpasswordforyouraccountWidget1.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedEllipse57Widget8.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedUnsplashjmURdhtm7NgWidget8.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/Generated081902060208Widget8.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedFrameWidget26.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedMarkLeeWidget9.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedGroup100Widget1.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedUpdateWidget8.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedMarklee0208gmailcomWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedGroup65Widget14.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedEditProfileWidget8.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedGroup67Widget16.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget1/generated/GeneratedWidget47.dart';

/* Frame confirm pw
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfirmpwWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget8(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget8(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget16(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget9(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget8(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget8(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget5(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget14()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget9(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget9(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget8(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget47(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget26(),
              ),
              Positioned(
                left: null,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget44(),
              ),
              Positioned(
                left: 40.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup100Widget1(),
              ),
              Positioned(
                left: 71.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 21.0,
                child: GeneratedCreateanewpasswordforyouraccountWidget1(),
              )
            ]),
      ),
    ));
  }
}
