import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedcoverwidget3/generated/GeneratedTransisiWidget5.dart';

/* Frame cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedChangesignupWidget2'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -172.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 726.0,
                  height: 812.0,
                  child: GeneratedTransisiWidget5(),
                )
              ]),
        ),
      ),
    ));
  }
}
