import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget20.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget21.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget22.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedBarWidget7.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedRectangleWidget69.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedRectangleWidget70.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget19.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedNavbarWidget11.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget24.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedFileWidget3.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget18.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedMelakukanendtoendrecruitmenprocessdimulaidarimencarikan1.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget1/generated/GeneratedTextWidget23.dart';

/* Frame info loker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfolokerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget11()),
              ),
              Positioned(
                left: null,
                top: 334.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 453.0,
                child: GeneratedRectangleWidget69(),
              ),
              Positioned(
                left: null,
                top: 116.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 208.0,
                child: GeneratedRectangleWidget70(),
              ),
              Positioned(
                left: null,
                top: 130.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 60.0,
                child: TransformHelper.translate(
                    x: -4.00, y: 0.00, z: 0, child: GeneratedFileWidget3()),
              ),
              Positioned(
                left: null,
                top: 210.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 99.0,
                child: TransformHelper.translate(
                    x: -53.50, y: 0.00, z: 0, child: GeneratedTextWidget18()),
              ),
              Positioned(
                left: null,
                top: 645.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -62.00, y: 0.00, z: 0, child: GeneratedTextWidget19()),
              ),
              Positioned(
                left: null,
                top: 347.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -66.50, y: 0.00, z: 0, child: GeneratedTextWidget20()),
              ),
              Positioned(
                left: null,
                top: 386.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 254.0,
                child: TransformHelper.translate(
                    x: -6.50,
                    y: 0.00,
                    z: 0,
                    child:
                        GeneratedMelakukanendtoendrecruitmenprocessdimulaidarimencarikan1()),
              ),
              Positioned(
                left: null,
                top: 679.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 42.0,
                child: TransformHelper.translate(
                    x: -67.00, y: 0.00, z: 0, child: GeneratedTextWidget21()),
              ),
              Positioned(
                left: null,
                top: 741.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: -97.00, y: 0.00, z: 0, child: GeneratedTextWidget22()),
              ),
              Positioned(
                left: null,
                top: 741.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 91.00, y: 0.00, z: 0, child: GeneratedTextWidget23()),
              ),
              Positioned(
                left: null,
                top: 679.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 81.50, y: 0.00, z: 0, child: GeneratedTextWidget24()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget7(),
              )
            ]),
      ),
    ));
  }
}
