import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedframe186widget/generated/GeneratedGroup87Widget2.dart';

/* Frame Frame 186
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame186Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 310.0,
        height: 222.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup87Widget2(),
              )
            ]),
      ),
    ));
  }
}
