import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup42Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup41Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup43Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup45Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedAddWidget5.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup44Widget1.dart';

/* Frame sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 124.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 50.0,
                child: GeneratedSignUpWidget1(),
              ),
              Positioned(
                left: 63.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup41Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup42Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup43Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup44Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup45Widget1(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedGroup57Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget5(),
              )
            ]),
      ),
    ));
  }
}
