import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedGroup68Widget2.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedVectorWidget297.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedSearchLokerWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedNavigationWidget31.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle23Widget31.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle4026Widget4.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedCategoryitemWidget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedHOMEMENUWidget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedVectorWidget294.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedTextWidget75.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedGroupWidget33.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedTextWidget76.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedGroupWidget32.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedTipsLokerWidget4.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordhomewidget/generated/GeneratedRectangle21Widget.dart';

/* Frame dashbord home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashbordhomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7146666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 268.0;

                  double percentHeight = 0.13916256157635468;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 113.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2853333333333333,
                        translateY: constraints.maxHeight * 0.24630541871921183,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle5Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7146666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 268.0;

                  double percentHeight = 0.13916256157635468;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 113.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2853333333333333,
                        translateY: constraints.maxHeight * 0.4187192118226601,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle22Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7146666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 268.0;

                  double percentHeight = 0.13916256157635468;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 113.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2853333333333333,
                        translateY: constraints.maxHeight * 0.5911330049261084,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle23Widget31())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7146666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 268.0;

                  double percentHeight = 0.13916256157635468;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 113.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2853333333333333,
                        translateY: constraints.maxHeight * 0.7635467980295566,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle24Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 375.0;

                  double percentHeight = 0.1724137931034483;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 140.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle7Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.288;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle21Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 11.0,
                right: 10.0,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedNavigationWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.05788177339901478,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCategoryitemWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.31527093596059114;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1724137931034483,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup68Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 126.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 35.0,
                child: GeneratedHOMEMENUWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.11466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 43.0;

                  double percentHeight = 0.05665024630541872;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 46.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.584,
                        translateY: constraints.maxHeight * 0.26354679802955666,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget294())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.05849859397399602;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.592,
                        y: constraints.maxHeight * 0.43472906403940886,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget32(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.11466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 43.0;

                  double percentHeight = 0.05295566502463054;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.584,
                        translateY: constraints.maxHeight * 0.6120689655172413,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget297())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13538468424479166;

                  final double height =
                      constraints.maxHeight * 0.059113272305192616;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.576,
                        y: constraints.maxHeight * 0.7783251231527094,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget33(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 273.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 53.00, y: 0.00, z: 0, child: GeneratedTextWidget75()),
              ),
              Positioned(
                left: null,
                top: 418.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 54.00, y: 0.00, z: 0, child: GeneratedTextWidget76()),
              ),
              Positioned(
                left: null,
                top: 557.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: 54.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedSearchLokerWidget()),
              ),
              Positioned(
                left: null,
                top: 697.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: 54.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedTipsLokerWidget4()),
              ),
              Positioned(
                left: 6.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 63.0,
                child: GeneratedRectangle4026Widget4(),
              )
            ]),
      ),
    ));
  }
}
