import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/Generated081902060208Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedUnsplashjmURdhtm7NgWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedGroup67Widget9.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedUsharealtWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedWidget23.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedBlurWidget25.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedEllipse57Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedEditProfileWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedMarkLeeWidget2.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedFrameWidget19.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedMarklee0208gmailcomWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedGroup97Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedUpdateWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/GeneratedGroup65Widget9.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget2/generated/Generatedonyour_markWidget2.dart';

/* Frame Profile Edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileEditWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget1(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget9(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget1(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget1(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget9()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget2(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget2(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget23(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget19(),
              ),
              Positioned(
                left: null,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget25(),
              ),
              Positioned(
                left: 33.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup97Widget(),
              )
            ]),
      ),
    ));
  }
}
