import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedCategoryitemWidget3.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedTextWidget80.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedTextWidget79.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedStatusIconsWidget35.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedTextWidget81.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedRectangle21Widget3.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup34Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup71Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup68Widget5.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup72Widget.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedUSERWidget1.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedRectangle4025Widget6.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/lokerapp/generateddashborduserwidget/generated/GeneratedSearchWidget4.dart';

/* Frame dashbord user
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashborduserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 375.0;

                  double percentHeight = 0.1724137931034483;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 140.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle7Widget4())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.288;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle21Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.05788177339901478,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCategoryitemWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.31527093596059114;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1724137931034483,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup68Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 38.0,
                child: GeneratedUSERWidget1(),
              ),
              Positioned(
                left: 126.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 40.0,
                child: GeneratedRectangle46Widget1(),
              ),
              Positioned(
                left: 145.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 23.0,
                child: GeneratedSearchWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.37333333333333335,
                        y: constraints.maxHeight * 0.3694581280788177,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup34Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.37333333333333335,
                        y: constraints.maxHeight * 0.4433497536945813,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup69Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.376,
                        y: constraints.maxHeight * 0.5172413793103449,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup70Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.37333333333333335,
                        y: constraints.maxHeight * 0.5911330049261084,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup71Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.37333333333333335,
                        y: constraints.maxHeight * 0.6650246305418719,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup72Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 262.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 23.0,
                child: TransformHelper.translate(
                    x: 56.00, y: 0.00, z: 0, child: GeneratedTextWidget79()),
              ),
              Positioned(
                left: null,
                top: 280.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 15.0,
                child: TransformHelper.translate(
                    x: 33.50, y: 0.00, z: 0, child: GeneratedTextWidget80()),
              ),
              Positioned(
                left: 140.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 278.0,
                child: GeneratedTextWidget81(),
              ),
              Positioned(
                left: null,
                top: 11.0,
                right: 10.0,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedStatusIconsWidget35(),
              ),
              Positioned(
                left: 6.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 63.0,
                child: GeneratedRectangle4025Widget6(),
              )
            ]),
      ),
    ));
  }
}
