import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedBarWidget20.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedGroup134Widget5.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedTextWidget57.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedTextWidget58.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedFileWidget9.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedTextWidget59.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedFileWidget8.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedNavbarWidget33.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedTextWidget60.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedGroup28Widget5.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget3/generated/GeneratedLatestfilesWidget7.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget33()),
              ),
              Positioned(
                left: null,
                top: 328.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 39.0,
                child: TransformHelper.translate(
                    x: -41.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLatestfilesWidget7()),
              ),
              Positioned(
                left: null,
                top: 603.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: TransformHelper.translate(
                    x: -126.50, y: 0.00, z: 0, child: GeneratedFileWidget8()),
              ),
              Positioned(
                left: null,
                top: 705.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: TransformHelper.translate(
                    x: -126.50, y: 0.00, z: 0, child: GeneratedFileWidget9()),
              ),
              Positioned(
                left: null,
                top: 389.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedTextWidget57()),
              ),
              Positioned(
                left: null,
                top: 491.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedTextWidget58()),
              ),
              Positioned(
                left: null,
                top: 593.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedTextWidget59()),
              ),
              Positioned(
                left: null,
                top: 695.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedTextWidget60()),
              ),
              Positioned(
                left: 26.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 176.0,
                child: GeneratedGroup28Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedGroup134Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget20(),
              )
            ]),
      ),
    ));
  }
}
