import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup127Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup126Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/Generated2Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup61Widget10.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup102Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedLokerWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/Generated2Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedBlockWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedTextWidget83.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup122Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedTextWidget82.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedGroup124Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofiluserswidget/generated/GeneratedBarWidget24.dart';

/* Frame profil users
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilusersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 296.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 44.0,
                child: TransformHelper.translate(
                    x: -96.50, y: 0.00, z: 0, child: GeneratedLokerWidget1()),
              ),
              Positioned(
                left: 12.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 152.0,
                child: GeneratedGroup61Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.256;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.36,
                        y: constraints.maxHeight * 0.9470443349753694,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle52Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06133333333333333;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3626666666666667,
                        y: constraints.maxHeight * 0.37438423645320196,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06133333333333333;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5146666666666667,
                        y: constraints.maxHeight * 0.6564039408866995,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup127Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 525.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 39.0,
                child: TransformHelper.translate(
                    x: -67.50, y: 0.00, z: 0, child: GeneratedGroup102Widget()),
              ),
              Positioned(
                left: null,
                top: 121.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 61.0,
                child: TransformHelper.translate(
                    x: 73.00, y: 0.00, z: 0, child: GeneratedGroup122Widget1()),
              ),
              Positioned(
                left: 162.0,
                top: 769.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 23.0,
                child: GeneratedBlockWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 23.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 23.0,
                child: Generated2Widget1(),
              ),
              Positioned(
                left: null,
                top: 337.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: 1.00, y: 0.00, z: 0, child: GeneratedGroup124Widget()),
              ),
              Positioned(
                left: null,
                top: 427.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: 1.00, y: 0.00, z: 0, child: GeneratedGroup126Widget()),
              ),
              Positioned(
                left: null,
                top: 566.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: 1.00, y: 0.00, z: 0, child: GeneratedTextWidget82()),
              ),
              Positioned(
                left: null,
                top: 656.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: 1.00, y: 0.00, z: 0, child: GeneratedTextWidget83()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget24(),
              )
            ]),
      ),
    ));
  }
}
