import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget11.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget15.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedBarWidget10.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget12.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup113Widget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget13.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup116Widget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedTIPSDRAFTWidget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget14.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup118Widget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedFrameWidget16.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup34Widget2.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedNavbarWidget17.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget2/generated/GeneratedGroup117Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame tipsloker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipslokerWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget17()),
              ),
              Positioned(
                left: null,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 590.0,
                child: GeneratedGroup34Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 35.0,
                child: GeneratedTIPSDRAFTWidget(),
              ),
              Positioned(
                left: null,
                top: 179.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 11.50, y: 0.00, z: 0, child: GeneratedGroup113Widget()),
              ),
              Positioned(
                left: null,
                top: 281.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 22.00, y: 0.00, z: 0, child: GeneratedGroup114Widget()),
              ),
              Positioned(
                left: null,
                top: 384.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 10.00, y: 0.00, z: 0, child: GeneratedGroup115Widget()),
              ),
              Positioned(
                left: null,
                top: 485.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 5.00, y: 0.00, z: 0, child: GeneratedGroup116Widget()),
              ),
              Positioned(
                left: null,
                top: 587.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 16.50, y: 0.00, z: 0, child: GeneratedGroup117Widget()),
              ),
              Positioned(
                left: null,
                top: 689.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 45.0,
                child: TransformHelper.translate(
                    x: 8.50, y: 0.00, z: 0, child: GeneratedGroup118Widget()),
              ),
              Positioned(
                left: 315.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget11(),
              ),
              Positioned(
                left: 315.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget12(),
              ),
              Positioned(
                left: 315.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget13(),
              ),
              Positioned(
                left: 315.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget14(),
              ),
              Positioned(
                left: 315.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget15(),
              ),
              Positioned(
                left: 315.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget10(),
              )
            ]),
      ),
    ));
  }
}
