import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedGroup30Widget9.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedMenuWidget56.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedRectangle4042Widget15.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedGroup76Widget3.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedNavigationWidget34.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget5/generated/GeneratedGroup130Widget1.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 503.0,
                child: GeneratedGroup30Widget9(),
              ),
              Positioned(
                left: null,
                top: 545.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 309.0,
                child: GeneratedGroup76Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedMenuWidget56(),
              ),
              Positioned(
                left: 7.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 17.0,
                child: GeneratedNavigationWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 14.0,
                child: GeneratedRectangle4042Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedGroup130Widget1(),
              )
            ]),
      ),
    ));
  }
}
