import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedGroup67Widget11.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedCreateanewpasswordforyouraccountWidget.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedUpdateWidget3.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/Generatedonyour_markWidget4.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedEditProfileWidget3.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedGroup65Widget11.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedMarklee0208gmailcomWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedWidget26.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedEllipse57Widget3.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedUsharealtWidget2.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/Generated081902060208Widget3.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedFrameWidget21.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedMarkLeeWidget4.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedGroup100Widget.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedRectangle31Widget4.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedBlurWidget28.dart';
import 'package:flutterapp/lokerapp/generatedconfirmpwwidget/generated/GeneratedUnsplashjmURdhtm7NgWidget3.dart';

/* Frame confirm pw
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfirmpwWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget3(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget3(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget11(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget4(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget3(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget3(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget2(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget11()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget3(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget26(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget21(),
              ),
              Positioned(
                left: null,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget28(),
              ),
              Positioned(
                left: 40.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup100Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 21.0,
                child: GeneratedCreateanewpasswordforyouraccountWidget(),
              )
            ]),
      ),
    ));
  }
}
