import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedUnsplashjmURdhtm7NgWidget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedUpdateWidget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedGroup97Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedFrameWidget24.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedEllipse57Widget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedRectangle31Widget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedUsharealtWidget3.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedMarklee0208gmailcomWidget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedGroup67Widget14.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/Generatedonyour_markWidget7.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedMarkLeeWidget7.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedEditProfileWidget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/Generated081902060208Widget6.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedGroup65Widget12.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedWidget37.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget5/generated/GeneratedBlurWidget38.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Profile Edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileEditWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget6(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget6(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget14(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget6(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget6(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget6(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget3(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget12()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget7(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget7(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget6(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget6(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget37(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget24(),
              ),
              Positioned(
                left: null,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget38(),
              ),
              Positioned(
                left: 33.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup97Widget1(),
              )
            ]),
      ),
    ));
  }
}
