import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4047Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedGroup146Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedSETTINGSLAYOUTWidget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedAddundefinedWidget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4045Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4046Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4044Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4025Widget5.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedGroup68Widget4.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedVectorWidget315.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedGroup147Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedGroup145Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedGroup149Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedRectangle4043Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedStatusIconsWidget33.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget1/generated/GeneratedCategoryitemWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame dashbord settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashbordsettingsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 375.0;

                  double percentHeight = 0.1724137931034483;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 140.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle7Widget2())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.288;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle21Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.05788177339901478,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCategoryitemWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.31527093596059114;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1724137931034483,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup68Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 35.0,
                child: GeneratedSETTINGSLAYOUTWidget(),
              ),
              Positioned(
                left: null,
                top: 11.0,
                right: 10.0,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedStatusIconsWidget33(),
              ),
              Positioned(
                left: 6.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 63.0,
                child: GeneratedRectangle4025Widget5(),
              ),
              Positioned(
                left: 131.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 100.0,
                child: GeneratedGroup146Widget1(),
              ),
              Positioned(
                left: 131.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 70.0,
                child: GeneratedGroup145Widget1(),
              ),
              Positioned(
                left: 131.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 70.0,
                child: GeneratedGroup147Widget1(),
              ),
              Positioned(
                left: 300.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedAddundefinedWidget1(),
              ),
              Positioned(
                left: 148.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle4043Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle4044Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle4045Widget(),
              ),
              Positioned(
                left: 268.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle4046Widget(),
              ),
              Positioned(
                left: 308.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle4047Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 30.0,
                child: GeneratedGroup149Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.02666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 10.0;

                  double percentHeight = 0.012315270935960592;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 10.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.408,
                        translateY: constraints.maxHeight * 0.4815270935960591,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget315())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
