import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup111Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget10.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup109Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup68Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedBarWidget6.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup108Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget6.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget8.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup110Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedGroup106Widget1.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedFrameWidget4.dart';
import 'package:flutterapp/lokerapp/generatedjobdraftwidget/generated/GeneratedJOBDRAFTWidget.dart';

/* Frame job draft
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJobdraftWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 169.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup68Widget1(),
              ),
              Positioned(
                left: null,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup111Widget1(),
              ),
              Positioned(
                left: null,
                top: 369.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup106Widget1(),
              ),
              Positioned(
                left: null,
                top: 469.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup108Widget1(),
              ),
              Positioned(
                left: null,
                top: 569.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup109Widget1(),
              ),
              Positioned(
                left: null,
                top: 669.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup110Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 35.0,
                child: GeneratedJOBDRAFTWidget(),
              ),
              Positioned(
                left: 318.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget(),
              ),
              Positioned(
                left: 318.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget2(),
              ),
              Positioned(
                left: 318.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget4(),
              ),
              Positioned(
                left: 318.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget6(),
              ),
              Positioned(
                left: 318.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget8(),
              ),
              Positioned(
                left: 318.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget6(),
              )
            ]),
      ),
    ));
  }
}
