import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget/generated/GeneratedAddWidget4.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget/generated/GeneratedRectangle4026Widget.dart';

/* Frame facebook
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFacebookWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 715.0,
                child: GeneratedRectangle4026Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 570.0,
                child: GeneratedAddWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedHeaderWidget(),
              )
            ]),
      ),
    ));
  }
}
