import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedUpdateWidget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedNavigationWidget29.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedMarkLeeWidget5.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/Generated081902060208Widget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedWidget33.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedMarklee0208gmailcomWidget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedEllipse57Widget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedFrameWidget22.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/Generatedonyour_markWidget5.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedEditProfileWidget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedDraftsundefinedWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedUnsplashjmURdhtm7NgWidget4.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedVectorWidget268.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedGroup134Widget7.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget3/generated/GeneratedGroup67Widget12.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Profile Edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileEditWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget4(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget4(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget12(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget4(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget4(),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget5(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget5(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget4(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget33(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedGroup134Widget7(),
              ),
              Positioned(
                left: 331.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDraftsundefinedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05354462178548177;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      20.079233169555664;

                  double percentHeight = 0.02472817839072843;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      20.079280853271484;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.029333333333333333,
                        translateY: constraints.maxHeight * 0.04926108374384237,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget268())
                  ]);
                }),
              ),
              Positioned(
                left: 10.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 17.0,
                child: GeneratedNavigationWidget29(),
              )
            ]),
      ),
    ));
  }
}
