import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedinfotipslokerwidget4/generated/GeneratedGroup66Widget19.dart';
import 'package:flutterapp/lokerapp/generatedinfotipslokerwidget4/generated/GeneratedBarWidget25.dart';
import 'package:flutterapp/lokerapp/generatedinfotipslokerwidget4/generated/GeneratedINFOTIPSLOKERWidget3.dart';
import 'package:flutterapp/lokerapp/generatedinfotipslokerwidget4/generated/GeneratedNavbarWidget41.dart';

/* Frame info tipsloker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfotipslokerWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 165.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 878.0,
                child: GeneratedGroup66Widget19(),
              ),
              Positioned(
                left: 35.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 35.0,
                child: GeneratedINFOTIPSLOKERWidget3(),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget41()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget25(),
              )
            ]),
      ),
    ));
  }
}
