import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup89Widget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedDeleteundefinedWidget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedVectorWidget124.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedFrameWidget18.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup88Widget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup87Widget1.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedRECENTWidget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/lokerapp/generatedrecentwidget/generated/GeneratedBarWidget12.dart';

/* Frame recent
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.2315270935960591,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup86Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.33497536945812806,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup87Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.43842364532019706,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup88Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.541871921182266,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup89Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.645320197044335,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup90Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.7487684729064039,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup91Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.0812807881773399;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.8522167487684729,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup92Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 39.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 38.0,
                child: GeneratedRECENTWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedDeleteundefinedWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.11733333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 44.0;

                  double percentHeight = 0.054187192118226604;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 44.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7973333333333333,
                        translateY: constraints.maxHeight * 0.8645320197044335,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget124())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget12(),
              ),
              Positioned(
                left: 300.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedFrameWidget18(),
              )
            ]),
      ),
    ));
  }
}
