import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedOrWidget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedGroup48Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedRectangle4019Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedLetssyouinWidget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedGroup101Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedEllipse55Widget8.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedGroup50Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedGroup49Widget2.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedAddWidget3.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedGroup136Widget.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedRectangle4040Widget.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget/generated/GeneratedEllipse55Widget7.dart';

/* Frame google
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGoogleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 358.0,
                child: GeneratedRectangle4019Widget2(),
              ),
              Positioned(
                left: null,
                top: 362.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLetssyouinWidget2()),
              ),
              Positioned(
                left: null,
                top: 662.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: -8.50, y: 0.00, z: 0, child: GeneratedOrWidget2()),
              ),
              Positioned(
                left: 28.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup48Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup49Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 213.0,
                child: GeneratedGroup50Widget2(),
              ),
              Positioned(
                left: 64.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget7(),
              ),
              Positioned(
                left: 64.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget8(),
              ),
              Positioned(
                left: 203.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 1.0,
                child: GeneratedLine5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 1.0,
                child: GeneratedLine6Widget2(),
              ),
              Positioned(
                left: 41.0,
                top: 701.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4040Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 239.99981689453125,
                height: 46.04328918457031,
                child: GeneratedGroup101Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 540.0,
                child: GeneratedGroup136Widget(),
              )
            ]),
      ),
    ));
  }
}
