import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedMelakukanendtoendrecruitmenprocessdimulaidarimencarikan2.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedRectangleWidget129.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedBarWidget15.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget48.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedNavbarWidget25.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget46.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget47.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget49.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget43.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedFileWidget7.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedRectangleWidget130.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget44.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget3/generated/GeneratedTextWidget45.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame info loker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfolokerWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget25()),
              ),
              Positioned(
                left: null,
                top: 334.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 453.0,
                child: GeneratedRectangleWidget129(),
              ),
              Positioned(
                left: null,
                top: 116.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 208.0,
                child: GeneratedRectangleWidget130(),
              ),
              Positioned(
                left: null,
                top: 130.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 60.0,
                child: TransformHelper.translate(
                    x: -4.00, y: 0.00, z: 0, child: GeneratedFileWidget7()),
              ),
              Positioned(
                left: null,
                top: 210.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 99.0,
                child: TransformHelper.translate(
                    x: -53.50, y: 0.00, z: 0, child: GeneratedTextWidget43()),
              ),
              Positioned(
                left: null,
                top: 645.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -54.00, y: 0.00, z: 0, child: GeneratedTextWidget44()),
              ),
              Positioned(
                left: null,
                top: 347.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -89.00, y: 0.00, z: 0, child: GeneratedTextWidget45()),
              ),
              Positioned(
                left: null,
                top: 386.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 254.0,
                child: TransformHelper.translate(
                    x: -6.50,
                    y: 0.00,
                    z: 0,
                    child:
                        GeneratedMelakukanendtoendrecruitmenprocessdimulaidarimencarikan2()),
              ),
              Positioned(
                left: null,
                top: 679.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 42.0,
                child: TransformHelper.translate(
                    x: -67.00, y: 0.00, z: 0, child: GeneratedTextWidget46()),
              ),
              Positioned(
                left: null,
                top: 741.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: -97.00, y: 0.00, z: 0, child: GeneratedTextWidget47()),
              ),
              Positioned(
                left: null,
                top: 741.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 91.00, y: 0.00, z: 0, child: GeneratedTextWidget48()),
              ),
              Positioned(
                left: null,
                top: 679.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 81.50, y: 0.00, z: 0, child: GeneratedTextWidget49()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget15(),
              )
            ]),
      ),
    ));
  }
}
