import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedAddundefinedWidget2.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup112Widget1.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedHomeWidget4.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup115Widget1.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedTextWidget78.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedHiUserWidget3.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup111Widget2.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedNavigationWidget32.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedAdvertisementWidget.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedCRUDHOMEPAGEWidget.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedTextWidget77.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedSearchFieldWidget.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedLatestInformationWidget3.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup114Widget1.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup116Widget1.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedGroup113Widget1.dart';
import 'package:flutterapp/lokerapp/generatedcrudhomewidget/generated/GeneratedEditundefinedWidget.dart';

/* Frame crud home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCrudhomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0000305175781,
                height: 110.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.2832512315270936,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup111Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.3620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup112Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.4408866995073892,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup113Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.5197044334975369,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup114Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.5985221674876847,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup115Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.04679802485874721;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6746666666666666,
                        y: constraints.maxHeight * 0.6773399014778325,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup116Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 35.0,
                child: GeneratedCRUDHOMEPAGEWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 53.0,
                child: GeneratedHomeWidget4(),
              ),
              Positioned(
                left: 259.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEditundefinedWidget(),
              ),
              Positioned(
                left: 229.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedAddundefinedWidget2(),
              ),
              Positioned(
                left: null,
                top: 235.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -95.50, y: 0.00, z: 0, child: GeneratedTextWidget77()),
              ),
              Positioned(
                left: null,
                top: 299.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -116.00, y: 0.00, z: 0, child: GeneratedTextWidget78()),
              ),
              Positioned(
                left: null,
                top: 363.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: -124.00, y: 0.00, z: 0, child: GeneratedHiUserWidget3()),
              ),
              Positioned(
                left: null,
                top: 427.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: -103.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedSearchFieldWidget()),
              ),
              Positioned(
                left: null,
                top: 491.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 32.0,
                child: TransformHelper.translate(
                    x: -91.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedAdvertisementWidget()),
              ),
              Positioned(
                left: null,
                top: 555.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: -75.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLatestInformationWidget3()),
              ),
              Positioned(
                left: 10.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 17.0,
                child: GeneratedNavigationWidget32(),
              )
            ]),
      ),
    ));
  }
}
