import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedAisyahcaramelWidget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedLetssyouinWidget3.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedDoyoungwijayagmailcomWidget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedAiscramelll12gmailcomWidget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedEllipse55Widget13.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedRectangle4019Widget3.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedRectangle4040Widget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroup140Widget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroup48Widget4.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroup49Widget3.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedOrWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroup101Widget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroup50Widget4.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedAddWidget7.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedLine6Widget4.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedDoywijayaWidget1.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGroupWidget19.dart';
import 'package:flutterapp/lokerapp/generatedgooglewidget1/generated/GeneratedGoogleTemplatesforStudents1Widget1.dart';

/* Frame google
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGoogleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 358.0,
                child: GeneratedRectangle4019Widget3(),
              ),
              Positioned(
                left: null,
                top: 362.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLetssyouinWidget3()),
              ),
              Positioned(
                left: null,
                top: 662.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: -8.50, y: 0.00, z: 0, child: GeneratedOrWidget3()),
              ),
              Positioned(
                left: 28.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup48Widget4(),
              ),
              Positioned(
                left: 28.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup49Widget3(),
              ),
              Positioned(
                left: 28.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 213.0,
                child: GeneratedGroup50Widget4(),
              ),
              Positioned(
                left: 64.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget13(),
              ),
              Positioned(
                left: 203.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 1.0,
                child: GeneratedLine5Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 1.0,
                child: GeneratedLine6Widget4(),
              ),
              Positioned(
                left: 41.0,
                top: 701.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4040Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 540.0,
                child: GeneratedGroup101Widget1(),
              ),
              Positioned(
                left: 117.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 49.0,
                child: GeneratedGoogleTemplatesforStudents1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.07733333333333334;

                  final double height =
                      constraints.maxHeight * 0.03571428571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.208,
                        y: constraints.maxHeight * 0.5763546798029556,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 19.0,
                child: GeneratedAisyahcaramelWidget1(),
              ),
              Positioned(
                left: 120.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 19.0,
                child: GeneratedDoywijayaWidget1(),
              ),
              Positioned(
                left: 78.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 33.0,
                child: GeneratedGroup140Widget1(),
              ),
              Positioned(
                left: 120.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 22.0,
                child: GeneratedAiscramelll12gmailcomWidget1(),
              ),
              Positioned(
                left: 120.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 22.0,
                child: GeneratedDoyoungwijayagmailcomWidget1(),
              )
            ]),
      ),
    ));
  }
}
