import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/Generated081902060208Widget2.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedFrameWidget20.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedGroup99Widget.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/Generatedonyour_markWidget3.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedMarkLeeWidget3.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedEmailMobileNumberWidget.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedUsharealtWidget1.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedUnsplashjmURdhtm7NgWidget2.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedGroup65Widget10.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedEllipse57Widget2.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedPleaseenteryourregisteredEmailormobilenumberThecodetore.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedUpdateWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedGroup67Widget10.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedEditProfileWidget2.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedWidget25.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedBlurWidget27.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget/generated/GeneratedMarklee0208gmailcomWidget2.dart';

/* Frame lupa pw
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLupapwWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget2(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget2(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget10(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget2(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget2(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget1(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget10()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget2(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget2(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget25(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget20(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget27(),
              ),
              Positioned(
                left: 33.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup99Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 16.0,
                child: GeneratedEmailMobileNumberWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 48.0,
                child:
                    GeneratedPleaseenteryourregisteredEmailormobilenumberThecodetore(),
              )
            ]),
      ),
    ));
  }
}
