import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget6/generated/GeneratedFrame182Widget2.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget6/generated/GeneratedNavigationWidget37.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: 10.0,
                      top: 11.0,
                      right: null,
                      bottom: null,
                      width: 355.0,
                      height: 17.0,
                      child: GeneratedNavigationWidget37(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 30.0,
              right: null,
              bottom: null,
              width: 440.0,
              height: 824.0,
              child: GeneratedFrame182Widget2(),
            )
          ]),
    ));
  }
}
