import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedEllipse55Widget5.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedWarningundefinedWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedNotifWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedGroup50Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedBlurWidget.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedGroup49Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedRectangle4019Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedAddWidget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedLetssyouinWidget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedOrWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/lokerapp/generatedchangesignupwidget1/generated/GeneratedEllipse55Widget4.dart';

/* Frame change sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChangesignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 358.0,
                child: GeneratedRectangle4019Widget1(),
              ),
              Positioned(
                left: null,
                top: 362.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLetssyouinWidget1()),
              ),
              Positioned(
                left: null,
                top: 662.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: -8.50, y: 0.00, z: 0, child: GeneratedOrWidget1()),
              ),
              Positioned(
                left: 28.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup48Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 54.0,
                child: GeneratedGroup49Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 213.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget4(),
              ),
              Positioned(
                left: 64.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEllipse55Widget5(),
              ),
              Positioned(
                left: 203.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 1.0,
                child: GeneratedLine5Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 41.0,
                top: 701.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget1(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: TransformHelper.translate(
                    x: -2.00, y: 0.00, z: 0, child: GeneratedBlurWidget()),
              ),
              Positioned(
                left: 32.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedNotifWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 88.0,
                child: GeneratedWarningundefinedWidget(),
              )
            ]),
      ),
    ));
  }
}
