import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget/generated/GeneratedNavigationWidget.dart';
import 'package:flutterapp/lokerapp/generatedpasangiklanwidget/generated/GeneratedGroup134Widget.dart';

/* Frame pasang iklan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPasangiklanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 82.0,
                      right: null,
                      bottom: null,
                      width: 341.0,
                      height: 590.0,
                      child: GeneratedGroup25Widget(),
                    ),
                    Positioned(
                      left: 10.0,
                      top: 11.0,
                      right: null,
                      bottom: null,
                      width: 355.0,
                      height: 17.0,
                      child: GeneratedNavigationWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 86.0,
              child: GeneratedGroup134Widget(),
            )
          ]),
    ));
  }
}
