import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedCategoryitemWidget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup148Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup146Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup145Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup68Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedRectangle4025Widget4.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedSETTINGSWidget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedGroup147Widget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedAddundefinedWidget.dart';
import 'package:flutterapp/lokerapp/generateddashbordsettingswidget/generated/GeneratedStatusIconsWidget32.dart';

/* Frame dashbord settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashbordsettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 375.0;

                  double percentHeight = 0.1724137931034483;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 140.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle7Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.288;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle21Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.05788177339901478,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCategoryitemWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.31527093596059114;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1724137931034483,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup68Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 38.0,
                child: GeneratedSETTINGSWidget(),
              ),
              Positioned(
                left: null,
                top: 11.0,
                right: 10.0,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedStatusIconsWidget32(),
              ),
              Positioned(
                left: 6.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 63.0,
                child: GeneratedRectangle4025Widget4(),
              ),
              Positioned(
                left: 282.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedAddundefinedWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 54.0,
                child: GeneratedGroup146Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 70.0,
                child: GeneratedGroup145Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 70.0,
                child: GeneratedGroup148Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 137.0,
                child: GeneratedGroup147Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.24;

                  final double height =
                      constraints.maxHeight * 0.11083742902783925;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5333333333333333,
                        y: constraints.maxHeight * 0.49137931034482757,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup21Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
