import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup111Widget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup110Widget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup108Widget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup109Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedMYJOBWidget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup106Widget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/lokerapp/generatedmyjobwidget/generated/GeneratedBarWidget5.dart';

/* Frame my job
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyjobWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 169.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: null,
                top: 269.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup111Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 35.0,
                child: GeneratedMYJOBWidget(),
              ),
              Positioned(
                left: null,
                top: 369.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedGroup106Widget()),
              ),
              Positioned(
                left: null,
                top: 469.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedGroup108Widget()),
              ),
              Positioned(
                left: null,
                top: 569.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: TransformHelper.translate(
                    x: -7.00, y: 0.00, z: 0, child: GeneratedGroup109Widget()),
              ),
              Positioned(
                left: null,
                top: 669.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedGroup110Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget5(),
              )
            ]),
      ),
    ));
  }
}
