import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedcoverwidget4/generated/GeneratedTransisiWidget6.dart';

/* Frame cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedCoverWidget5'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 84.0,
                  top: 302.0,
                  right: null,
                  bottom: null,
                  width: 207.0,
                  height: 207.0,
                  child: GeneratedTransisiWidget6(),
                )
              ]),
        ),
      ),
    ));
  }
}
