import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup42Widget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedAddWidget10.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup43Widget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedSignUpWidget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup45Widget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup44Widget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup57Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget3/generated/GeneratedGroup41Widget2.dart';

/* Frame sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: 124.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 50.0,
                child: GeneratedSignUpWidget2(),
              ),
              Positioned(
                left: 63.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup41Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup42Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup43Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup44Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 37.0,
                child: GeneratedGroup45Widget2(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedGroup57Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 40.0,
                child: GeneratedAddWidget10(),
              )
            ]),
      ),
    ));
  }
}
