import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedGroup73Widget1.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedRectangle4026Widget2.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedGroup71Widget.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedAddWidget8.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedRectangle4025Widget2.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedRectangle4027Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedRectangle4028Widget1.dart';
import 'package:flutterapp/lokerapp/generatedfacebookwidget1/generated/GeneratedSignuptofacebookWidget1.dart';

/* Frame facebook
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFacebookWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 97.0,
                child: GeneratedRectangle4025Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 715.0,
                child: GeneratedRectangle4026Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 570.0,
                child: GeneratedRectangle4027Widget1(),
              ),
              Positioned(
                left: null,
                top: 183.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: -3.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedSignuptofacebookWidget1()),
              ),
              Positioned(
                left: 62.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 36.911766052246094,
                child: GeneratedGroup71Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 36.911766052246094,
                child: GeneratedGroup73Widget1(),
              ),
              Positioned(
                left: 71.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 32.0,
                child: GeneratedAddWidget8(),
              ),
              Positioned(
                left: 9.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 83.0,
                child: GeneratedRectangle4028Widget1(),
              )
            ]),
      ),
    ));
  }
}
