import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup138Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup134Widget2.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedLokerWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup119Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup137Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedBarWidget11.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup136Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedTipsLokerWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedGroup73Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedVectorWidget103.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedEllipse56Widget3.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/GeneratedMarkLeeWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget/generated/Generatedonyour_markWidget.dart';

/* Frame Profile Edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileEditWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 111.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 152.0,
                child: GeneratedEllipse56Widget3(),
              ),
              Positioned(
                left: null,
                top: 289.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 3.00, y: 0.00, z: 0, child: GeneratedMarkLeeWidget()),
              ),
              Positioned(
                left: null,
                top: 317.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 32.0,
                child: TransformHelper.translate(
                    x: 1.50,
                    y: 0.00,
                    z: 0,
                    child: Generatedonyour_markWidget()),
              ),
              Positioned(
                left: null,
                top: 572.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 35.0,
                child: TransformHelper.translate(
                    x: -101.00, y: 0.00, z: 0, child: GeneratedLokerWidget()),
              ),
              Positioned(
                left: null,
                top: 572.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 32.0,
                child: TransformHelper.translate(
                    x: 101.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedTipsLokerWidget1()),
              ),
              Positioned(
                left: 27.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 31.0,
                child: GeneratedGroup73Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399014778325122;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10133333333333333,
                        translateY: constraints.maxHeight * 0.5073891625615764,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget103())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4266666666666667;

                  final double height =
                      constraints.maxHeight * 0.12488725032712439;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.5751231527093597,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup93Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 467.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 101.41000366210938,
                child: TransformHelper.translate(
                    x: 92.50, y: 0.00, z: 0, child: GeneratedGroup119Widget()),
              ),
              Positioned(
                left: 150.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedGroup137Widget1(),
              ),
              Positioned(
                left: 281.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedGroup138Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedGroup136Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedGroup134Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget11(),
              )
            ]),
      ),
    ));
  }
}
