import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedWidget16.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/Generated081902060208Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedFrameWidget17.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedMarklee0208gmailcomWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedGroup65Widget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedEditProfileWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedEllipse57Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedUnsplashjmURdhtm7NgWidget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedGroup67Widget2.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/Generatedonyour_markWidget1.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedGroup122Widget.dart';
import 'package:flutterapp/lokerapp/generatedprofileeditwidget1/generated/GeneratedMarkLeeWidget1.dart';

/* Frame Profile Edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileEditWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedGroup122Widget(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget1()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget16(),
              ),
              Positioned(
                left: 212.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget17(),
              )
            ]),
      ),
    ));
  }
}
