import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget4/generated/GeneratedNavbarWidget38.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget4/generated/GeneratedGroup135Widget2.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget4/generated/GeneratedLatestfilesWidget8.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget4/generated/GeneratedGroup34Widget4.dart';
import 'package:flutterapp/lokerapp/generatedtipslokerwidget4/generated/GeneratedBarWidget23.dart';

/* Frame tipsloker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipslokerWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget38()),
              ),
              Positioned(
                left: null,
                top: 108.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 39.0,
                child: TransformHelper.translate(
                    x: -91.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedLatestfilesWidget8()),
              ),
              Positioned(
                left: null,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 590.0,
                child: GeneratedGroup34Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedGroup135Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedBarWidget23(),
              )
            ]),
      ),
    ));
  }
}
