import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine37Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedNavbarWidget13.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedFileWidget4.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine38Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedGroup139Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine36Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine31Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine33Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedRectangleWidget75.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedRectangleWidget74.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine34Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine39Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine28Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedTextWidget26.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine40Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedTextWidget25.dart';
import 'package:flutterapp/lokerapp/generatedinfolokerwidget2/generated/GeneratedLine35Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame info loker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfolokerWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 243, 243, 243),
                ),
              ),
              Positioned(
                left: null,
                top: 18.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -144.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNavbarWidget13()),
              ),
              Positioned(
                left: null,
                top: 334.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 453.0,
                child: GeneratedRectangleWidget74(),
              ),
              Positioned(
                left: null,
                top: 116.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 208.0,
                child: GeneratedRectangleWidget75(),
              ),
              Positioned(
                left: null,
                top: 130.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 60.0,
                child: TransformHelper.translate(
                    x: -4.00, y: 0.00, z: 0, child: GeneratedFileWidget4()),
              ),
              Positioned(
                left: null,
                top: 645.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -62.00, y: 0.00, z: 0, child: GeneratedTextWidget25()),
              ),
              Positioned(
                left: null,
                top: 347.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: -66.50, y: 0.00, z: 0, child: GeneratedTextWidget26()),
              ),
              Positioned(
                left: 30.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 0.0,
                child: GeneratedLine24Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 1.0,
                child: GeneratedLine27Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 391.02984619140625,
                right: null,
                bottom: null,
                width: 280.00189208984375,
                height: 1.0,
                child: GeneratedLine28Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 401.03350830078125,
                right: null,
                bottom: null,
                width: 280.00189208984375,
                height: 1.0,
                child: GeneratedLine33Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 411.03350830078125,
                right: null,
                bottom: null,
                width: 280.00189208984375,
                height: 1.0,
                child: GeneratedLine34Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 150.00332641601562,
                height: 1.0,
                child: GeneratedLine25Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 1.0,
                child: GeneratedLine31Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 1.0,
                child: GeneratedLine37Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 1.0,
                child: GeneratedLine35Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 1.0,
                child: GeneratedLine39Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 1.0,
                child: GeneratedLine32Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 1.0,
                child: GeneratedLine38Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 1.0,
                child: GeneratedLine36Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 1.0,
                child: GeneratedLine40Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 150.0033416748047,
                height: 1.0,
                child: GeneratedLine26Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 94.0,
                child: GeneratedGroup139Widget(),
              )
            ]),
      ),
    ));
  }
}
