import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedGroup134Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedTextWidget4.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedFileWidget1.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedFileWidget.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedGroup28Widget2.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedLatestfilesWidget2.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedTextWidget1.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedTextWidget3.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedBarWidget.dart';
import 'package:flutterapp/lokerapp/generatedsearchwidget/generated/GeneratedNavbarWidget.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 243, 243, 243),
                      ),
                    ),
                    Positioned(
                      left: null,
                      top: 18.0,
                      right: null,
                      bottom: null,
                      width: 46.0,
                      height: 46.0,
                      child: TransformHelper.translate(
                          x: -144.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedNavbarWidget()),
                    ),
                    Positioned(
                      left: null,
                      top: 328.0,
                      right: null,
                      bottom: null,
                      width: 222.0,
                      height: 39.0,
                      child: TransformHelper.translate(
                          x: -41.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedLatestfilesWidget2()),
                    ),
                    Positioned(
                      left: null,
                      top: 603.0,
                      right: null,
                      bottom: null,
                      width: 60.0,
                      height: 60.0,
                      child: TransformHelper.translate(
                          x: -126.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedFileWidget()),
                    ),
                    Positioned(
                      left: null,
                      top: 705.0,
                      right: null,
                      bottom: null,
                      width: 60.0,
                      height: 60.0,
                      child: TransformHelper.translate(
                          x: -126.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedFileWidget1()),
                    ),
                    Positioned(
                      left: null,
                      top: 389.0,
                      right: null,
                      bottom: null,
                      width: 335.0,
                      height: 80.0,
                      child: TransformHelper.translate(
                          x: -7.00,
                          y: 0.00,
                          z: 0,
                          child: GeneratedTextWidget1()),
                    ),
                    Positioned(
                      left: null,
                      top: 491.0,
                      right: null,
                      bottom: null,
                      width: 335.0,
                      height: 80.0,
                      child: TransformHelper.translate(
                          x: -7.00,
                          y: 0.00,
                          z: 0,
                          child: GeneratedTextWidget2()),
                    ),
                    Positioned(
                      left: null,
                      top: 593.0,
                      right: null,
                      bottom: null,
                      width: 335.0,
                      height: 80.0,
                      child: TransformHelper.translate(
                          x: -7.00,
                          y: 0.00,
                          z: 0,
                          child: GeneratedTextWidget3()),
                    ),
                    Positioned(
                      left: null,
                      top: 695.0,
                      right: null,
                      bottom: null,
                      width: 335.0,
                      height: 80.0,
                      child: TransformHelper.translate(
                          x: -7.00,
                          y: 0.00,
                          z: 0,
                          child: GeneratedTextWidget4()),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 117.0,
                      right: null,
                      bottom: null,
                      width: 335.0,
                      height: 176.0,
                      child: GeneratedGroup28Widget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 94.0,
                      child: GeneratedBarWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 86.0,
              child: GeneratedGroup134Widget1(),
            )
          ]),
    ));
  }
}
