import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedMarklee0208gmailcomWidget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedRectangle31Widget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedWidget46.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedMarkLeeWidget8.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedPleaseenteryourregisteredEmailormobilenumberThecodetore1.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedUnsplashjmURdhtm7NgWidget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedGroup65Widget13.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedUpdateWidget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedEditProfileWidget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedEllipse57Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedUsharealtWidget4.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedGroup99Widget1.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedEmailMobileNumberWidget1.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedBlurWidget43.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedGroup67Widget15.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/Generatedonyour_markWidget8.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/Generated081902060208Widget7.dart';
import 'package:flutterapp/lokerapp/generatedlupapwwidget1/generated/GeneratedFrameWidget25.dart';

/* Frame lupa pw
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLupapwWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -298.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 566.0,
                child: GeneratedEllipse57Widget7(),
              ),
              Positioned(
                left: 117.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 142.0,
                child: GeneratedUnsplashjmURdhtm7NgWidget7(),
              ),
              Positioned(
                left: 36.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 378.0,
                child: GeneratedGroup67Widget15(),
              ),
              Positioned(
                left: 53.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 40.0,
                child: GeneratedRectangle31Widget7(),
              ),
              Positioned(
                left: 166.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 28.0,
                child: GeneratedUpdateWidget7(),
              ),
              Positioned(
                left: 148.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 25.0,
                child: GeneratedEditProfileWidget7(),
              ),
              Positioned(
                left: 315.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedUsharealtWidget4(),
              ),
              Positioned(
                left: null,
                top: 13.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -151.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedGroup65Widget13()),
              ),
              Positioned(
                left: 51.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedMarkLeeWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 26.0,
                child: Generatedonyour_markWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 26.0,
                child: GeneratedMarklee0208gmailcomWidget7(),
              ),
              Positioned(
                left: 47.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: Generated081902060208Widget7(),
              ),
              Positioned(
                left: 47.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedWidget46(),
              ),
              Positioned(
                left: 209.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedFrameWidget25(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBlurWidget43(),
              ),
              Positioned(
                left: 33.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 222.0,
                child: GeneratedGroup99Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 16.0,
                child: GeneratedEmailMobileNumberWidget1(),
              ),
              Positioned(
                left: 42.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 48.0,
                child:
                    GeneratedPleaseenteryourregisteredEmailormobilenumberThecodetore1(),
              )
            ]),
      ),
    ));
  }
}
